name: Code Interpreter Docker Image
on:
  push:
    branches:
      - main
      - dev
      - feature/**
    paths:
      - .github/workflows/code-interpreter.yml
  workflow_dispatch:

jobs:
  build-containers:
    strategy:
      matrix:
        include:
          - tag: linux-x64
            runs-on: ubuntu-24.04
            platform: linux/amd64
          - tag: linux-arm64
            runs-on: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USERNAME }} ${{ vars.DOCKER_REGISTRY }} --password-stdin

      - name: Create inline Dockerfile
        run: |
          cat <<'EOF' > Dockerfile
          FROM mcr.microsoft.com/dotnet/sdk:10.0
          WORKDIR /app
          EOF

      - name: Build and push container
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          provenance: false
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/code-interpreter:r-${{ github.run_number }}-${{ matrix.tag }}

  docker-manifest:
    needs: build-containers
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USERNAME }} ${{ vars.DOCKER_REGISTRY }} --password-stdin
        
      - name: Create and push manifest for run number tag
        run: |
          docker manifest create --amend ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/code-interpreter:r-${{ github.run_number }} \
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/code-interpreter:r-${{ github.run_number }}-linux-x64 \
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/code-interpreter:r-${{ github.run_number }}-linux-arm64
          
          docker manifest push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/code-interpreter:r-${{ github.run_number }}

      - name: Create and push latest manifest (main branch only)
        if: github.ref_name == 'main'
        run: |
          docker manifest create --amend ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/code-interpreter:latest \
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/code-interpreter:r-${{ github.run_number }}-linux-x64 \
            ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/code-interpreter:r-${{ github.run_number }}-linux-arm64
          
          docker manifest push ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_NAMESPACE }}/code-interpreter:latest
